// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class BadmakeprescriptionTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void badmakeprescription() {
    // Test name: Bad make prescription
    // Step # | name | target | value
    // 1 | open | https://asclepius-client-management.netlify.app/ | 
    driver.get("https://asclepius-client-management.netlify.app/");
    // 2 | click | css=.MuiButton-label | 
    driver.findElement(By.cssSelector(".MuiButton-label")).click();
    // 3 | type | xpath=//div[@id='root']/main/div/div[2]/div/form/div/div/div/input | hotNurseGF
    driver.findElement(By.xpath("//div[@id=\'root\']/main/div/div[2]/div/form/div/div/div/input")).sendKeys("hotNurseGF");
    // 4 | type | xpath=//div[@id='root']/main/div/div[2]/div/form/div[2]/div/div/input | orange
    driver.findElement(By.xpath("//div[@id=\'root\']/main/div/div[2]/div/form/div[2]/div/div/input")).sendKeys("orange");
    // 5 | sendKeys | css=.Mui-focused > .MuiInputBase-input | ${KEY_ENTER}
    driver.findElement(By.cssSelector(".Mui-focused > .MuiInputBase-input")).sendKeys(Keys.ENTER);
    // 6 | verifyElementPresent | css=.nav-btns:nth-child(2) | 
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".nav-btns:nth-child(2)"));
      assert(elements.size() > 0);
    }
    // 7 | click | css=.nav-btns:nth-child(2) | 
    driver.findElement(By.cssSelector(".nav-btns:nth-child(2)")).click();
    // 8 | click | css=.MuiButton-contained > .MuiButton-label | 
    driver.findElement(By.cssSelector(".MuiButton-contained > .MuiButton-label")).click();
    // 9 | verifyText | css=p:nth-child(2) | Patient ID:
    assertThat(driver.findElement(By.cssSelector("p:nth-child(2)")).getText(), is("Patient ID:"));
    // 10 | click | css=.MuiButtonBase-root:nth-child(8) > .MuiButton-label | 
    driver.findElement(By.cssSelector(".MuiButtonBase-root:nth-child(8) > .MuiButton-label")).click();
    // 11 | verifyText | css=p | SOME ERROR OCCURED
    assertThat(driver.findElement(By.cssSelector("p")).getText(), is("SOME ERROR OCCURED"));
    // 12 | close |  | 
    driver.close();
  }
}
