// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class GoodremovetypeofmedicationfrominventoryTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void goodremovetypeofmedicationfrominventory() {
    // Test name: Good remove type of medication from inventory
    // Step # | name | target | value
    // 1 | open | https://asclepius-client-management.netlify.app/ | 
    driver.get("https://asclepius-client-management.netlify.app/");
    // 2 | click | css=.MuiButtonBase-root | 
    driver.findElement(By.cssSelector(".MuiButtonBase-root")).click();
    // 3 | setWindowSize | 1051x813 | 
    driver.manage().window().setSize(new Dimension(1051, 813));
    // 4 | click | css=.Mui-focused > .MuiInputBase-input | 
    driver.findElement(By.cssSelector(".Mui-focused > .MuiInputBase-input")).click();
    // 5 | type | xpath=//div[@id='root']/main/div/div[2]/div/form/div/div/div/input | Lpjj
    driver.findElement(By.xpath("//div[@id=\'root\']/main/div/div[2]/div/form/div/div/div/input")).sendKeys("Lpjj");
    // 6 | type | xpath=//div[@id='root']/main/div/div[2]/div/form/div[2]/div/div/input | chocolate
    driver.findElement(By.xpath("//div[@id=\'root\']/main/div/div[2]/div/form/div[2]/div/div/input")).sendKeys("chocolate");
    // 7 | sendKeys | css=.Mui-focused > .MuiInputBase-input | ${KEY_ENTER}
    driver.findElement(By.cssSelector(".Mui-focused > .MuiInputBase-input")).sendKeys(Keys.ENTER);
    // 8 | click | css=.nav-btns:nth-child(4) | 
    driver.findElement(By.cssSelector(".nav-btns:nth-child(4)")).click();
    // 9 | mouseOver | css=.MuiButtonBase-root:nth-child(3) > .MuiButton-label | 
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiButtonBase-root:nth-child(3) > .MuiButton-label"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 10 | click | css=.MuiButtonBase-root:nth-child(3) > .MuiButton-label | 
    driver.findElement(By.cssSelector(".MuiButtonBase-root:nth-child(3) > .MuiButton-label")).click();
    // 11 | mouseOut | css=.MuiButtonBase-root:nth-child(3) > .MuiButton-label | 
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    // 12 | click | xpath=//div[@id='root']/main/div/div[2]/div[2]/div/button[2]/span | 
    driver.findElement(By.xpath("//div[@id=\'root\']/main/div/div[2]/div[2]/div/button[2]/span")).click();
    // 13 | click | css=path | 
    driver.findElement(By.cssSelector("path")).click();
    // 14 | verifyElementPresent | id=react-select-2-option-3 | 
    {
      List<WebElement> elements = driver.findElements(By.id("react-select-2-option-3"));
      assert(elements.size() > 0);
    }
    // 15 | mouseOver | id=react-select-2-option-3 | 
    {
      WebElement element = driver.findElement(By.id("react-select-2-option-3"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 16 | click | id=react-select-2-option-3 | 
    driver.findElement(By.id("react-select-2-option-3")).click();
    // 17 | click | css=.MuiButton-outlined:nth-child(2) > .MuiButton-label | 
    driver.findElement(By.cssSelector(".MuiButton-outlined:nth-child(2) > .MuiButton-label")).click();
    // 18 | verifyElementPresent | css=.MuiButtonBase-root:nth-child(5) > .MuiButton-label | 
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".MuiButtonBase-root:nth-child(5) > .MuiButton-label"));
      assert(elements.size() > 0);
    }
    // 19 | mouseOver | css=.MuiButtonBase-root:nth-child(5) > .MuiButton-label | 
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiButtonBase-root:nth-child(5) > .MuiButton-label"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 20 | click | css=.MuiButtonBase-root:nth-child(5) > .MuiButton-label | 
    driver.findElement(By.cssSelector(".MuiButtonBase-root:nth-child(5) > .MuiButton-label")).click();
    // 21 | verifyText | css=p | Medication has been removed!
    assertThat(driver.findElement(By.cssSelector("p")).getText(), is("Medication has been removed!"));
    // 22 | click | css=form .MuiButton-label | 
    driver.findElement(By.cssSelector("form .MuiButton-label")).click();
    // 23 | click | css=.nav-btns:nth-child(2) | 
    driver.findElement(By.cssSelector(".nav-btns:nth-child(2)")).click();
    // 24 | verifyElementNotPresent | css=tr:nth-child(5) > td:nth-child(2) | 
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("tr:nth-child(5) > td:nth-child(2)"));
      assert(elements.size() == 0);
    }
    // 25 | close |  | 
    driver.close();
  }
}
