// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class BadLoginTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void badLogin() {
    // Test name: Bad Login
    // Step # | name | target | value
    // 1 | open | https://asclepius-client-management.netlify.app/ | 
    driver.get("https://asclepius-client-management.netlify.app/");
    // 2 | click | css=.MuiButtonBase-root | 
    driver.findElement(By.cssSelector(".MuiButtonBase-root")).click();
    // 3 | setWindowSize | 1051x814 | 
    driver.manage().window().setSize(new Dimension(1051, 814));
    // 4 | click | xpath=//div[@id='root']/main/div/div[2]/div/form/div/div/div/input | 
    driver.findElement(By.xpath("//div[@id=\'root\']/main/div/div[2]/div/form/div/div/div/input")).click();
    // 5 | type | xpath=//div[@id='root']/main/div/div[2]/div/form/div/div/div/input | baduser
    driver.findElement(By.xpath("//div[@id=\'root\']/main/div/div[2]/div/form/div/div/div/input")).sendKeys("baduser");
    // 6 | verifyValue | xpath=//div[@id='root']/main/div/div[2]/div/form/div/div/div/input | baduser
    {
      String value = driver.findElement(By.xpath("//div[@id=\'root\']/main/div/div[2]/div/form/div/div/div/input")).getAttribute("value");
      assertThat(value, is("baduser"));
    }
    // 7 | click | xpath=//div[@id='root']/main/div/div[2]/div/form/div[2]/div/div/input | 
    driver.findElement(By.xpath("//div[@id=\'root\']/main/div/div[2]/div/form/div[2]/div/div/input")).click();
    // 8 | type | xpath=//div[@id='root']/main/div/div[2]/div/form/div[2]/div/div/input | badpassword
    driver.findElement(By.xpath("//div[@id=\'root\']/main/div/div[2]/div/form/div[2]/div/div/input")).sendKeys("badpassword");
    // 9 | click | css=.MuiButton-outlined > .MuiButton-label | 
    driver.findElement(By.cssSelector(".MuiButton-outlined > .MuiButton-label")).click();
    // 10 | verifyText | id=errorMessage | Username or Password is incorrect.
    assertThat(driver.findElement(By.id("errorMessage")).getText(), is("Username or Password is incorrect."));
    // 11 | close |  | 
    driver.close();
  }
}
