// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class GoodOrderMedicationsTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void goodOrderMedications() {
    // Test name: Good Order Medications
    // Step # | name | target | value
    // 1 | open | https://asclepius-client-management.netlify.app/ | 
    driver.get("https://asclepius-client-management.netlify.app/");
    // 2 | click | css=.MuiButtonBase-root | 
    driver.findElement(By.cssSelector(".MuiButtonBase-root")).click();
    // 3 | setWindowSize | 1054x816 | 
    driver.manage().window().setSize(new Dimension(1054, 816));
    // 4 | click | css=.Mui-focused > .MuiInputBase-input | 
    driver.findElement(By.cssSelector(".Mui-focused > .MuiInputBase-input")).click();
    // 5 | type | xpath=//div[@id='root']/main/div/div[2]/div/form/div/div/div/input | Lpjj
    driver.findElement(By.xpath("//div[@id=\'root\']/main/div/div[2]/div/form/div/div/div/input")).sendKeys("Lpjj");
    // 6 | type | xpath=//div[@id='root']/main/div/div[2]/div/form/div[2]/div/div/input | chocolate
    driver.findElement(By.xpath("//div[@id=\'root\']/main/div/div[2]/div/form/div[2]/div/div/input")).sendKeys("chocolate");
    // 7 | sendKeys | css=.Mui-focused > .MuiInputBase-input | ${KEY_ENTER}
    driver.findElement(By.cssSelector(".Mui-focused > .MuiInputBase-input")).sendKeys(Keys.ENTER);
    // 8 | click | css=.nav-btns:nth-child(3) | 
    driver.findElement(By.cssSelector(".nav-btns:nth-child(3)")).click();
    // 9 | click | css=.css-ackcql | 
    driver.findElement(By.cssSelector(".css-ackcql")).click();
    // 10 | pause | 1000 | 
    try {
      Thread.sleep(1000);
    } catch (InterruptedException e) {
      e.printStackTrace();
    }
    // 11 | click | css=.css-ackcql | 
    driver.findElement(By.cssSelector(".css-ackcql")).click();
    // 12 | mouseOver | css=.css-ackcql | 
    {
      WebElement element = driver.findElement(By.cssSelector(".css-ackcql"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 13 | mouseOver | id=react-select-5-option-0 | 
    {
      WebElement element = driver.findElement(By.id("react-select-5-option-0"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 14 | click | id=react-select-5-option-0 | 
    driver.findElement(By.id("react-select-5-option-0")).click();
    // 15 | click | css=.MuiInputBase-input | 
    driver.findElement(By.cssSelector(".MuiInputBase-input")).click();
    // 16 | type | css=.MuiInputBase-input | 1
    driver.findElement(By.cssSelector(".MuiInputBase-input")).sendKeys("1");
    // 17 | click | css=.make-order-form-container | 
    driver.findElement(By.cssSelector(".make-order-form-container")).click();
    // 18 | mouseOver | css=.MuiButton-contained > .MuiButton-label | 
    {
      WebElement element = driver.findElement(By.cssSelector(".MuiButton-contained > .MuiButton-label"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    // 19 | click | css=.MuiButton-contained > .MuiButton-label | 
    driver.findElement(By.cssSelector(".MuiButton-contained > .MuiButton-label")).click();
    // 20 | close |  | 
    driver.close();
  }
}
