// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class GoodNurseLoginTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
  //																												//
  //									FUNTIONAL REQUIREMENT RTM ID - (TC-16)										//
  //																												//
  ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
  @Test
  public void goodNurseLogin() {
    // Test name: Good Nurse Login
    // Step # | name | target | value
    // 1 | open | https://asclepius-client-management.netlify.app/ | 
    driver.get("https://asclepius-client-management.netlify.app/");
    // 2 | click | css=.MuiButton-label | 
    driver.findElement(By.cssSelector(".MuiButton-label")).click();
    // 3 | type | xpath=//div[@id='root']/main/div/div[2]/div/form/div/div/div/input | hotNurseGF
    driver.findElement(By.xpath("//div[@id=\'root\']/main/div/div[2]/div/form/div/div/div/input")).sendKeys("hotNurseGF");
    // 4 | verifyValue | xpath=//div[@id='root']/main/div/div[2]/div/form/div/div/div/input | hotNurseGF
    {
      String value = driver.findElement(By.xpath("//div[@id=\'root\']/main/div/div[2]/div/form/div/div/div/input")).getAttribute("value");
      assertThat(value, is("hotNurseGF"));
    }
    // 5 | type | xpath=//div[@id='root']/main/div/div[2]/div/form/div[2]/div/div/input | orange
    driver.findElement(By.xpath("//div[@id=\'root\']/main/div/div[2]/div/form/div[2]/div/div/input")).sendKeys("orange");
    // 6 | verifyValue | xpath=//div[@id='root']/main/div/div[2]/div/form/div[2]/div/div/input | orange
    {
      String value = driver.findElement(By.xpath("//div[@id=\'root\']/main/div/div[2]/div/form/div[2]/div/div/input")).getAttribute("value");
      assertThat(value, is("orange"));
    }
    // 7 | sendKeys | css=.Mui-focused > .MuiInputBase-input | ${KEY_ENTER}
    driver.findElement(By.cssSelector(".Mui-focused > .MuiInputBase-input")).sendKeys(Keys.ENTER);
    // 8 | verifyElementPresent | css=.MuiButtonBase-root:nth-child(3) > .MuiButton-label | 
    {
      List<WebElement> elements = driver.findElements(By.cssSelector(".MuiButtonBase-root:nth-child(3) > .MuiButton-label"));
      assert(elements.size() > 0);
    }
    // 9 | click | css=.MuiButton-outlined > .MuiButton-label | 
    driver.findElement(By.cssSelector(".MuiButton-outlined > .MuiButton-label")).click();
    // 10 | verifyText | css=h3 | Your patient and pharmaceuticals information system
    assertThat(driver.findElement(By.cssSelector("h3")).getText(), is("Your patient and pharmaceuticals information system"));
    // 11 | close |  | 
    driver.close();
  }
}
