// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class NurseNotesTestTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
  //																												//
  //									FUNTIONAL REQUIREMENT RTM ID - (TC-19)										//
  //																												//
  ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
  @Test
  public void nurseNotesTest() {
    driver.get("http://localhost:3000/login");
    driver.manage().window().setSize(new Dimension(1374, 1314));
    driver.findElement(By.xpath("//div[@id=\'root\']/main/div/div[2]/div/form/div/div/div/input")).click();
    driver.findElement(By.xpath("//div[@id=\'root\']/main/div/div[2]/div/form/div/div/div/input")).sendKeys("mjane");
    driver.findElement(By.xpath("//div[@id=\'root\']/main/div/div[2]/div/form/div[2]/div/div/input")).click();
    {
      WebElement element = driver.findElement(By.xpath("//div[@id=\'root\']/main/div/div[2]/div/form/button/span"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.xpath("//div[@id=\'root\']/main/div/div[2]/div/form/div[2]/div/div/input")).sendKeys("abcde");
    driver.findElement(By.xpath("//div[@id=\'root\']/main/div/div[2]/div/form/button/span")).click();
    driver.findElement(By.xpath("//div[@id=\'root\']/main/div/div[2]/div[2]/div/div/div/div/button/span/h3[2]")).click();
    driver.findElement(By.xpath("//div[@id=\'root\']/main/div/div[2]/div[2]/div/div/div[2]/div[3]/button/span")).click();
    driver.findElement(By.xpath("//div[@id=\'root\']/main/div/div[2]/div[2]/div/div/div[2]/div/div/div/input")).click();
    driver.findElement(By.xpath("//div[@id=\'root\']/main/div/div[2]/div[2]/div/div/div[2]/div/div/div/input")).sendKeys("test");
    driver.findElement(By.xpath("//div[@id=\'root\']/main/div/div[2]/div[2]/div/div/div[2]/button/span")).click();
    {
      WebElement element = driver.findElement(By.xpath("//div[@id=\'root\']/main/div/div/header/div/div/a/button/span"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    driver.findElement(By.xpath("//div[@id=\'root\']/main/div/div/header/div/div/a/button/span")).click();
    driver.close();
  }
}
