// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class GoodPharmacistLoginTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
  //																												//
  //									FUNTIONAL REQUIREMENT RTM ID - (TC-30)										//
  //																												//
  ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
  @Test
  public void goodPharmacistLogin() {
    // Test name: Good Pharmacist Login
    // Step # | name | target | value
    // 1 | open | https://asclepius-client-management.netlify.app/ | 
    driver.get("https://asclepius-client-management.netlify.app/");
    // 2 | click | css=.MuiButtonBase-root | 
    driver.findElement(By.cssSelector(".MuiButtonBase-root")).click();
    // 3 | setWindowSize | 1052x815 | 
    driver.manage().window().setSize(new Dimension(1052, 815));
    // 4 | click | xpath=//div[@id='root']/main/div/div[2]/div/form/div/div/div/input | 
    driver.findElement(By.xpath("//div[@id=\'root\']/main/div/div[2]/div/form/div/div/div/input")).click();
    // 5 | type | xpath=//div[@id='root']/main/div/div[2]/div/form/div/div/div/input | Lpjj
    driver.findElement(By.xpath("//div[@id=\'root\']/main/div/div[2]/div/form/div/div/div/input")).sendKeys("Lpjj");
    // 6 | verifyValue | xpath=//div[@id='root']/main/div/div[2]/div/form/div/div/div/input | Lpjj
    {
      String value = driver.findElement(By.xpath("//div[@id=\'root\']/main/div/div[2]/div/form/div/div/div/input")).getAttribute("value");
      assertThat(value, is("Lpjj"));
    }
    // 7 | click | xpath=//div[@id='root']/main/div/div[2]/div/form/div[2]/div/div/input | 
    driver.findElement(By.xpath("//div[@id=\'root\']/main/div/div[2]/div/form/div[2]/div/div/input")).click();
    // 8 | type | xpath=//div[@id='root']/main/div/div[2]/div/form/div[2]/div/div/input | chocolate
    driver.findElement(By.xpath("//div[@id=\'root\']/main/div/div[2]/div/form/div[2]/div/div/input")).sendKeys("chocolate");
    // 9 | verifyValue | xpath=//div[@id='root']/main/div/div[2]/div/form/div[2]/div/div/input | chocolate
    {
      String value = driver.findElement(By.xpath("//div[@id=\'root\']/main/div/div[2]/div/form/div[2]/div/div/input")).getAttribute("value");
      assertThat(value, is("chocolate"));
    }
    // 10 | click | css=.MuiButton-outlined > .MuiButton-label | 
    driver.findElement(By.cssSelector(".MuiButton-outlined > .MuiButton-label")).click();
    // 11 | waitForElementPresent | css=h3 | 30000
    {
      WebDriverWait wait = new WebDriverWait(driver, 30);
      wait.until(ExpectedConditions.presenceOfElementLocated(By.cssSelector("h3")));
    }
    // 12 | verifyText | css=h3 | Hello, Pharmacist Logan Jones
    assertThat(driver.findElement(By.cssSelector("h3")).getText(), is("Hello, Pharmacist Logan Jones"));
    // 13 | click | css=.MuiButton-outlined > .MuiButton-label | 
    driver.findElement(By.cssSelector(".MuiButton-outlined > .MuiButton-label")).click();
    // 14 | verifyText | css=h3 | Your patient and pharmaceuticals information system
    assertThat(driver.findElement(By.cssSelector("h3")).getText(), is("Your patient and pharmaceuticals information system"));
    // 15 | close |  | 
    driver.close();
  }
}
